//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Экзамен_3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тарифы
    {
        public int ID_Тарифа { get; set; }
        public Nullable<int> Код_Города { get; set; }
        public string Название_города { get; set; }
        public Nullable<int> Тариф_стоимость_1_мин { get; set; }
        public string Сост_оплаты { get; set; }
    
        public virtual Разговор Разговор { get; set; }
        public virtual Телефон Телефон { get; set; }
    }
}
