//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Экзамен_3_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Телефон
    {
        public int ID_Телефона { get; set; }
        public Nullable<int> Номер_договора { get; set; }
        public Nullable<System.DateTime> Дата_установки { get; set; }
        public Nullable<int> Телефон1 { get; set; }
    
        public virtual Абонент Абонент { get; set; }
        public virtual Тарифы Тарифы { get; set; }
    }
}
